PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB090 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB090-USUARIO .
    FIELD /PTLOMS/TB090-CERT_ID .
    FIELD /PTLOMS/TB090-DT_VALIDADE .
    FIELD /PTLOMS/TB090-ERNAM .
    FIELD /PTLOMS/TB090-ERDAT .
    FIELD /PTLOMS/TB090-ERZEIT .
    FIELD /PTLOMS/TB090-AENAM .
    FIELD /PTLOMS/TB090-AEDAT .
    FIELD /PTLOMS/TB090-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB090-USUARIO .
    FIELD /PTLOMS/TB090-CERT_ID .
    FIELD /PTLOMS/TB090-DT_VALIDADE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
