PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB104 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB104-ID_NOTIFICACAO .
    FIELD /PTLOMS/TB104-TIPO_NOTIFICACAO .
    FIELD /PTLOMS/TB104-TIPO_EVENTO .
    FIELD /PTLOMS/TB104-TIPO_DOCUMENTO .
    FIELD /PTLOMS/TB104-DOCUMENTO .
    FIELD /PTLOMS/TB104-ITEM_DOCUMENTO .
    FIELD /PTLOMS/TB104-ORDEM .
    FIELD /PTLOMS/TB104-OPERACAO .
    FIELD /PTLOMS/TB104-TIPO_OBJETO .
    FIELD /PTLOMS/TB104-OBJETO .
    FIELD /PTLOMS/TB104-ID_LISTA .
    FIELD /PTLOMS/TB104-TITULO .
    FIELD /PTLOMS/TB104-MENSAGEM .
    FIELD /PTLOMS/TB104-USUARIO_CRIACAO .
    FIELD /PTLOMS/TB104-DATA_CRIACAO .
    FIELD /PTLOMS/TB104-HORA_CRIACAO .
    FIELD /PTLOMS/TB104-AENAM .
    FIELD /PTLOMS/TB104-AEDAT .
    FIELD /PTLOMS/TB104-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB104-ID_NOTIFICACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
