PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB092 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB092-USUARIO .
    FIELD /PTLOMS/TB092-REGIAO_ID .
    FIELD /PTLOMS/TB092-ERNAM .
    FIELD /PTLOMS/TB092-ERDAT .
    FIELD /PTLOMS/TB092-ERZEIT .
    FIELD /PTLOMS/TB092-AENAM .
    FIELD /PTLOMS/TB092-AEDAT .
    FIELD /PTLOMS/TB092-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB092-USUARIO .
    FIELD /PTLOMS/TB092-REGIAO_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
