PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /PTLOMS/TB033-USUARIO_SAP .
    FIELD /PTLOMS/TB033-ANEXO_ORDEM .
    FIELD /PTLOMS/TB033-ANEXO_LOCL .
    FIELD /PTLOMS/TB033-ANEXO_EQUI .
    FIELD /PTLOMS/TB033-DESPACHO_ORDEM .
    FIELD /PTLOMS/TB033-DESPACHO_OPER .
    FIELD /PTLOMS/TB033-CALC_TRAB_REAL .
    FIELD /PTLOMS/TB033-CONF_DT_LANC .
    FIELD /PTLOMS/TB033-CONFIRMACAO .
    FIELD /PTLOMS/TB033-QTDE_REG_SINC .
    FIELD /PTLOMS/TB033-QTDE_ORDEM .
    FIELD /PTLOMS/TB033-MOT_INT_TRAB .
    FIELD /PTLOMS/TB033-VARIANT .
    FIELD /PTLOMS/TB033-CHAVE_MODELO .
    FIELD /PTLOMS/TB033-APONT_MANUAL .
    FIELD /PTLOMS/TB033-TIPO_ATIVIDADE .
    FIELD /PTLOMS/TB033-ANOS_RETROATIVOS .
    FIELD /PTLOMS/TB033-ULT_DOC_MEDICAO .
    FIELD /PTLOMS/TB033-VERSAO_APP .
    FIELD /PTLOMS/TB033-CESTO .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
  module detail_pai.
 endchain.
