PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB073 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE z_busca_descricao.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB073-APLICACAO .
    FIELD /PTLOMS/TB073-GRUPO .
    FIELD /PTLOMS/TB073-DESCRICAO .
    FIELD /PTLOMS/TB073-ERNAM .
    FIELD /PTLOMS/TB073-ERDAT .
    FIELD /PTLOMS/TB073-ERZEIT .
    FIELD /PTLOMS/TB073-AENAM .
    FIELD /PTLOMS/TB073-AEDAT .
    FIELD /PTLOMS/TB073-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB073-APLICACAO .
    FIELD /PTLOMS/TB073-GRUPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
