PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB093 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB093-EQUNR .
    FIELD /PTLOMS/TB093-SKILL_ID .
    FIELD /PTLOMS/TB093-NIVEL_MIN .
    FIELD /PTLOMS/TB093-ERNAM .
    FIELD /PTLOMS/TB093-ERDAT .
    FIELD /PTLOMS/TB093-ERZEIT .
    FIELD /PTLOMS/TB093-AENAM .
    FIELD /PTLOMS/TB093-AEDAT .
    FIELD /PTLOMS/TB093-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB093-EQUNR .
    FIELD /PTLOMS/TB093-SKILL_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
