*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /PTLOMS/V001....................................*
FORM GET_DATA_/PTLOMS/V001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB002 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V001 .
/PTLOMS/V001-MANDT =
/PTLOMS/TB002-MANDT .
/PTLOMS/V001-BUKRS =
/PTLOMS/TB002-BUKRS .
/PTLOMS/V001-WERKS =
/PTLOMS/TB002-WERKS .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = /PTLOMS/TB002-BUKRS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-BUTXT =
T001-BUTXT .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB002-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB002 WHERE
  BUKRS = /PTLOMS/V001-BUKRS AND
  WERKS = /PTLOMS/V001-WERKS .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB002 WHERE
  BUKRS = /PTLOMS/V001-BUKRS AND
  WERKS = /PTLOMS/V001-WERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB002.
    ENDIF.
/PTLOMS/TB002-MANDT =
/PTLOMS/V001-MANDT .
/PTLOMS/TB002-BUKRS =
/PTLOMS/V001-BUKRS .
/PTLOMS/TB002-WERKS =
/PTLOMS/V001-WERKS .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB002 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V001-UPD_FLAG,
STATUS_/PTLOMS/V001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V001.
  SELECT SINGLE * FROM /PTLOMS/TB002 WHERE
BUKRS = /PTLOMS/V001-BUKRS AND
WERKS = /PTLOMS/V001-WERKS .
/PTLOMS/V001-MANDT =
/PTLOMS/TB002-MANDT .
/PTLOMS/V001-BUKRS =
/PTLOMS/TB002-BUKRS .
/PTLOMS/V001-WERKS =
/PTLOMS/TB002-WERKS .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = /PTLOMS/TB002-BUKRS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V001-BUTXT .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB002-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V001-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V001-BUKRS TO
/PTLOMS/TB002-BUKRS .
MOVE /PTLOMS/V001-WERKS TO
/PTLOMS/TB002-WERKS .
MOVE /PTLOMS/V001-MANDT TO
/PTLOMS/TB002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V001 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB002-MANDT =
/PTLOMS/V001-MANDT .
/PTLOMS/TB002-BUKRS =
/PTLOMS/V001-BUKRS .
/PTLOMS/TB002-WERKS =
/PTLOMS/V001-WERKS .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = /PTLOMS/TB002-BUKRS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V001-BUTXT .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB002-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V001-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V001-NAME1 .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V002....................................*
FORM GET_DATA_/PTLOMS/V002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB003 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V002 .
/PTLOMS/V002-MANDT =
/PTLOMS/TB003-MANDT .
/PTLOMS/V002-IWERK =
/PTLOMS/TB003-IWERK .
/PTLOMS/V002-INGRP =
/PTLOMS/TB003-INGRP .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB003-IWERK .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-NAME1 =
T001W-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T024I WHERE
IWERK = /PTLOMS/TB003-IWERK AND
INGRP = /PTLOMS/TB003-INGRP .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-INNAM =
T024I-INNAM .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB003 WHERE
  IWERK = /PTLOMS/V002-IWERK AND
  INGRP = /PTLOMS/V002-INGRP .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB003 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB003 WHERE
  IWERK = /PTLOMS/V002-IWERK AND
  INGRP = /PTLOMS/V002-INGRP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB003.
    ENDIF.
/PTLOMS/TB003-MANDT =
/PTLOMS/V002-MANDT .
/PTLOMS/TB003-IWERK =
/PTLOMS/V002-IWERK .
/PTLOMS/TB003-INGRP =
/PTLOMS/V002-INGRP .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB003 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB003 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V002-UPD_FLAG,
STATUS_/PTLOMS/V002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V002.
  SELECT SINGLE * FROM /PTLOMS/TB003 WHERE
IWERK = /PTLOMS/V002-IWERK AND
INGRP = /PTLOMS/V002-INGRP .
/PTLOMS/V002-MANDT =
/PTLOMS/TB003-MANDT .
/PTLOMS/V002-IWERK =
/PTLOMS/TB003-IWERK .
/PTLOMS/V002-INGRP =
/PTLOMS/TB003-INGRP .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB003-IWERK .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V002-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T024I WHERE
IWERK = /PTLOMS/TB003-IWERK AND
INGRP = /PTLOMS/TB003-INGRP .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-INNAM =
T024I-INNAM .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V002-INNAM .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V002-IWERK TO
/PTLOMS/TB003-IWERK .
MOVE /PTLOMS/V002-INGRP TO
/PTLOMS/TB003-INGRP .
MOVE /PTLOMS/V002-MANDT TO
/PTLOMS/TB003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V002 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB003-MANDT =
/PTLOMS/V002-MANDT .
/PTLOMS/TB003-IWERK =
/PTLOMS/V002-IWERK .
/PTLOMS/TB003-INGRP =
/PTLOMS/V002-INGRP .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB003-IWERK .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V002-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T024I WHERE
IWERK = /PTLOMS/TB003-IWERK AND
INGRP = /PTLOMS/TB003-INGRP .
    IF SY-SUBRC EQ 0.
/PTLOMS/V002-INNAM =
T024I-INNAM .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V002-INNAM .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V003....................................*
FORM GET_DATA_/PTLOMS/V003.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB004 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V003 .
/PTLOMS/V003-MANDT =
/PTLOMS/TB004-MANDT .
/PTLOMS/V003-WERKS =
/PTLOMS/TB004-WERKS .
/PTLOMS/V003-BEBER =
/PTLOMS/TB004-BEBER .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB004-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-NAME1 =
T001W-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T357 WHERE
WERKS = /PTLOMS/TB004-WERKS AND
BEBER = /PTLOMS/TB004-BEBER .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-FING =
T357-FING .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V003.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V003 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V003.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V003-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB004 WHERE
  WERKS = /PTLOMS/V003-WERKS AND
  BEBER = /PTLOMS/V003-BEBER .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB004 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB004 WHERE
  WERKS = /PTLOMS/V003-WERKS AND
  BEBER = /PTLOMS/V003-BEBER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB004.
    ENDIF.
/PTLOMS/TB004-MANDT =
/PTLOMS/V003-MANDT .
/PTLOMS/TB004-WERKS =
/PTLOMS/V003-WERKS .
/PTLOMS/TB004-BEBER =
/PTLOMS/V003-BEBER .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB004 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB004 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V003-UPD_FLAG,
STATUS_/PTLOMS/V003-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V003.
  SELECT SINGLE * FROM /PTLOMS/TB004 WHERE
WERKS = /PTLOMS/V003-WERKS AND
BEBER = /PTLOMS/V003-BEBER .
/PTLOMS/V003-MANDT =
/PTLOMS/TB004-MANDT .
/PTLOMS/V003-WERKS =
/PTLOMS/TB004-WERKS .
/PTLOMS/V003-BEBER =
/PTLOMS/TB004-BEBER .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB004-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V003-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T357 WHERE
WERKS = /PTLOMS/TB004-WERKS AND
BEBER = /PTLOMS/TB004-BEBER .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-FING =
T357-FING .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V003-FING .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V003 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V003-WERKS TO
/PTLOMS/TB004-WERKS .
MOVE /PTLOMS/V003-BEBER TO
/PTLOMS/TB004-BEBER .
MOVE /PTLOMS/V003-MANDT TO
/PTLOMS/TB004-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB004'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB004 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB004'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V003 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB004-MANDT =
/PTLOMS/V003-MANDT .
/PTLOMS/TB004-WERKS =
/PTLOMS/V003-WERKS .
/PTLOMS/TB004-BEBER =
/PTLOMS/V003-BEBER .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB004-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V003-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM T357 WHERE
WERKS = /PTLOMS/TB004-WERKS AND
BEBER = /PTLOMS/TB004-BEBER .
    IF SY-SUBRC EQ 0.
/PTLOMS/V003-FING =
T357-FING .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V003-FING .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V004....................................*
FORM GET_DATA_/PTLOMS/V004.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB005 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V004 .
/PTLOMS/V004-MANDT =
/PTLOMS/TB005-MANDT .
/PTLOMS/V004-OBJID =
/PTLOMS/TB005-OBJID .
/PTLOMS/V004-LEARR =
/PTLOMS/TB005-LEARR .
/PTLOMS/V004-WERKS =
/PTLOMS/TB005-WERKS .
/PTLOMS/V004-ARBPL =
/PTLOMS/TB005-ARBPL .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V004-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V004.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V004 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V004.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V004-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB005 WHERE
  OBJID = /PTLOMS/V004-OBJID .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB005 WHERE
  OBJID = /PTLOMS/V004-OBJID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB005.
    ENDIF.
/PTLOMS/TB005-MANDT =
/PTLOMS/V004-MANDT .
/PTLOMS/TB005-OBJID =
/PTLOMS/V004-OBJID .
/PTLOMS/TB005-LEARR =
/PTLOMS/V004-LEARR .
/PTLOMS/TB005-WERKS =
/PTLOMS/V004-WERKS .
/PTLOMS/TB005-ARBPL =
/PTLOMS/V004-ARBPL .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB005 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V004-UPD_FLAG,
STATUS_/PTLOMS/V004-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V004.
  SELECT SINGLE * FROM /PTLOMS/TB005 WHERE
OBJID = /PTLOMS/V004-OBJID .
/PTLOMS/V004-MANDT =
/PTLOMS/TB005-MANDT .
/PTLOMS/V004-OBJID =
/PTLOMS/TB005-OBJID .
/PTLOMS/V004-LEARR =
/PTLOMS/TB005-LEARR .
/PTLOMS/V004-WERKS =
/PTLOMS/TB005-WERKS .
/PTLOMS/V004-ARBPL =
/PTLOMS/TB005-ARBPL .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V004-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V004-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V004 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V004-OBJID TO
/PTLOMS/TB005-OBJID .
MOVE /PTLOMS/V004-MANDT TO
/PTLOMS/TB005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V004 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB005-MANDT =
/PTLOMS/V004-MANDT .
/PTLOMS/TB005-OBJID =
/PTLOMS/V004-OBJID .
/PTLOMS/TB005-LEARR =
/PTLOMS/V004-LEARR .
/PTLOMS/TB005-WERKS =
/PTLOMS/V004-WERKS .
/PTLOMS/TB005-ARBPL =
/PTLOMS/V004-ARBPL .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V004-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V004-NAME1 .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V005....................................*
FORM GET_DATA_/PTLOMS/V005.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB006 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V005 .
/PTLOMS/V005-MANDT =
/PTLOMS/TB006-MANDT .
/PTLOMS/V005-FLTYP =
/PTLOMS/TB006-FLTYP .
    SELECT SINGLE * FROM T370F WHERE
FLTYP = /PTLOMS/TB006-FLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370F_T WHERE
FLTYP = T370F-FLTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V005-TYPTX =
T370F_T-TYPTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V005.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V005 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V005.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V005-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB006 WHERE
  FLTYP = /PTLOMS/V005-FLTYP .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB006 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB006 WHERE
  FLTYP = /PTLOMS/V005-FLTYP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB006.
    ENDIF.
/PTLOMS/TB006-MANDT =
/PTLOMS/V005-MANDT .
/PTLOMS/TB006-FLTYP =
/PTLOMS/V005-FLTYP .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB006 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB006 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V005-UPD_FLAG,
STATUS_/PTLOMS/V005-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V005.
  SELECT SINGLE * FROM /PTLOMS/TB006 WHERE
FLTYP = /PTLOMS/V005-FLTYP .
/PTLOMS/V005-MANDT =
/PTLOMS/TB006-MANDT .
/PTLOMS/V005-FLTYP =
/PTLOMS/TB006-FLTYP .
    SELECT SINGLE * FROM T370F WHERE
FLTYP = /PTLOMS/TB006-FLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370F_T WHERE
FLTYP = T370F-FLTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V005-TYPTX =
T370F_T-TYPTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V005-TYPTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V005-TYPTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V005 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V005-FLTYP TO
/PTLOMS/TB006-FLTYP .
MOVE /PTLOMS/V005-MANDT TO
/PTLOMS/TB006-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB006'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB006 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB006'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V005 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB006-MANDT =
/PTLOMS/V005-MANDT .
/PTLOMS/TB006-FLTYP =
/PTLOMS/V005-FLTYP .
    SELECT SINGLE * FROM T370F WHERE
FLTYP = /PTLOMS/TB006-FLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370F_T WHERE
FLTYP = T370F-FLTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V005-TYPTX =
T370F_T-TYPTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V005-TYPTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V005-TYPTX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V006....................................*
FORM GET_DATA_/PTLOMS/V006.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB007 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V006 .
/PTLOMS/V006-MANDT =
/PTLOMS/TB007-MANDT .
/PTLOMS/V006-EQTYP =
/PTLOMS/TB007-EQTYP .
    SELECT SINGLE * FROM T370T WHERE
EQTYP = /PTLOMS/TB007-EQTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370U WHERE
EQTYP = T370T-EQTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V006-TYPTX =
T370U-TYPTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V006.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V006 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V006.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V006-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB007 WHERE
  EQTYP = /PTLOMS/V006-EQTYP .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB007 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB007 WHERE
  EQTYP = /PTLOMS/V006-EQTYP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB007.
    ENDIF.
/PTLOMS/TB007-MANDT =
/PTLOMS/V006-MANDT .
/PTLOMS/TB007-EQTYP =
/PTLOMS/V006-EQTYP .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB007 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB007 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V006-UPD_FLAG,
STATUS_/PTLOMS/V006-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V006.
  SELECT SINGLE * FROM /PTLOMS/TB007 WHERE
EQTYP = /PTLOMS/V006-EQTYP .
/PTLOMS/V006-MANDT =
/PTLOMS/TB007-MANDT .
/PTLOMS/V006-EQTYP =
/PTLOMS/TB007-EQTYP .
    SELECT SINGLE * FROM T370T WHERE
EQTYP = /PTLOMS/TB007-EQTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370U WHERE
EQTYP = T370T-EQTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V006-TYPTX =
T370U-TYPTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V006-TYPTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V006-TYPTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V006 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V006-EQTYP TO
/PTLOMS/TB007-EQTYP .
MOVE /PTLOMS/V006-MANDT TO
/PTLOMS/TB007-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB007'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB007 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB007'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V006 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB007-MANDT =
/PTLOMS/V006-MANDT .
/PTLOMS/TB007-EQTYP =
/PTLOMS/V006-EQTYP .
    SELECT SINGLE * FROM T370T WHERE
EQTYP = /PTLOMS/TB007-EQTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370U WHERE
EQTYP = T370T-EQTYP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V006-TYPTX =
T370U-TYPTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V006-TYPTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V006-TYPTX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V007....................................*
FORM GET_DATA_/PTLOMS/V007.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB008 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V007 .
/PTLOMS/V007-MANDT =
/PTLOMS/TB008-MANDT .
/PTLOMS/V007-EQART =
/PTLOMS/TB008-EQART .
    SELECT SINGLE * FROM T370K WHERE
EQART = /PTLOMS/TB008-EQART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370K_T WHERE
EQART = T370K-EQART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V007-EARTX =
T370K_T-EARTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V007.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V007 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V007.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V007-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB008 WHERE
  EQART = /PTLOMS/V007-EQART .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB008 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB008 WHERE
  EQART = /PTLOMS/V007-EQART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB008.
    ENDIF.
/PTLOMS/TB008-MANDT =
/PTLOMS/V007-MANDT .
/PTLOMS/TB008-EQART =
/PTLOMS/V007-EQART .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB008 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB008 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V007-UPD_FLAG,
STATUS_/PTLOMS/V007-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V007.
  SELECT SINGLE * FROM /PTLOMS/TB008 WHERE
EQART = /PTLOMS/V007-EQART .
/PTLOMS/V007-MANDT =
/PTLOMS/TB008-MANDT .
/PTLOMS/V007-EQART =
/PTLOMS/TB008-EQART .
    SELECT SINGLE * FROM T370K WHERE
EQART = /PTLOMS/TB008-EQART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370K_T WHERE
EQART = T370K-EQART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V007-EARTX =
T370K_T-EARTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V007-EARTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V007-EARTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V007 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V007-EQART TO
/PTLOMS/TB008-EQART .
MOVE /PTLOMS/V007-MANDT TO
/PTLOMS/TB008-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB008'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB008 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB008'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V007 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB008-MANDT =
/PTLOMS/V007-MANDT .
/PTLOMS/TB008-EQART =
/PTLOMS/V007-EQART .
    SELECT SINGLE * FROM T370K WHERE
EQART = /PTLOMS/TB008-EQART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T370K_T WHERE
EQART = T370K-EQART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V007-EARTX =
T370K_T-EARTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V007-EARTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V007-EARTX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V008....................................*
FORM GET_DATA_/PTLOMS/V008.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB009 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V008 .
/PTLOMS/V008-MANDT =
/PTLOMS/TB009-MANDT .
/PTLOMS/V008-QMART =
/PTLOMS/TB009-QMART .
    SELECT SINGLE * FROM TQ80 WHERE
QMART = /PTLOMS/TB009-QMART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMTYP =
TQ80-QMTYP .
/PTLOMS/V008-RBNR =
TQ80-RBNR .
      SELECT SINGLE * FROM TQ80_T WHERE
QMART = TQ80-QMART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMARTX =
TQ80_T-QMARTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V008.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V008 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V008.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V008-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB009 WHERE
  QMART = /PTLOMS/V008-QMART .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB009 WHERE
  QMART = /PTLOMS/V008-QMART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB009.
    ENDIF.
/PTLOMS/TB009-MANDT =
/PTLOMS/V008-MANDT .
/PTLOMS/TB009-QMART =
/PTLOMS/V008-QMART .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB009 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V008-UPD_FLAG,
STATUS_/PTLOMS/V008-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V008.
  SELECT SINGLE * FROM /PTLOMS/TB009 WHERE
QMART = /PTLOMS/V008-QMART .
/PTLOMS/V008-MANDT =
/PTLOMS/TB009-MANDT .
/PTLOMS/V008-QMART =
/PTLOMS/TB009-QMART .
    SELECT SINGLE * FROM TQ80 WHERE
QMART = /PTLOMS/TB009-QMART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMTYP =
TQ80-QMTYP .
/PTLOMS/V008-RBNR =
TQ80-RBNR .
      SELECT SINGLE * FROM TQ80_T WHERE
QMART = TQ80-QMART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMARTX =
TQ80_T-QMARTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V008-QMARTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V008-QMTYP .
      CLEAR /PTLOMS/V008-RBNR .
      CLEAR /PTLOMS/V008-QMARTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V008 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V008-QMART TO
/PTLOMS/TB009-QMART .
MOVE /PTLOMS/V008-MANDT TO
/PTLOMS/TB009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V008 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB009-MANDT =
/PTLOMS/V008-MANDT .
/PTLOMS/TB009-QMART =
/PTLOMS/V008-QMART .
    SELECT SINGLE * FROM TQ80 WHERE
QMART = /PTLOMS/TB009-QMART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMTYP =
TQ80-QMTYP .
/PTLOMS/V008-RBNR =
TQ80-RBNR .
      SELECT SINGLE * FROM TQ80_T WHERE
QMART = TQ80-QMART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V008-QMARTX =
TQ80_T-QMARTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V008-QMARTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V008-QMTYP .
      CLEAR /PTLOMS/V008-RBNR .
      CLEAR /PTLOMS/V008-QMARTX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V009....................................*
FORM GET_DATA_/PTLOMS/V009.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB010 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V009 .
/PTLOMS/V009-MANDT =
/PTLOMS/TB010-MANDT .
/PTLOMS/V009-AUART =
/PTLOMS/TB010-AUART .
    SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V009-AUTYP =
T003O-AUTYP .
      SELECT SINGLE * FROM T003P WHERE
AUART = T003O-AUART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V009-TXT =
T003P-TXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V009.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V009 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V009.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V009-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB010 WHERE
  AUART = /PTLOMS/V009-AUART .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB010 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB010 WHERE
  AUART = /PTLOMS/V009-AUART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB010.
    ENDIF.
/PTLOMS/TB010-MANDT =
/PTLOMS/V009-MANDT .
/PTLOMS/TB010-AUART =
/PTLOMS/V009-AUART .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB010 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB010 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V009-UPD_FLAG,
STATUS_/PTLOMS/V009-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V009.
  SELECT SINGLE * FROM /PTLOMS/TB010 WHERE
AUART = /PTLOMS/V009-AUART .
/PTLOMS/V009-MANDT =
/PTLOMS/TB010-MANDT .
/PTLOMS/V009-AUART =
/PTLOMS/TB010-AUART .
    SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V009-AUTYP =
T003O-AUTYP .
      SELECT SINGLE * FROM T003P WHERE
AUART = T003O-AUART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V009-TXT =
T003P-TXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V009-TXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V009-AUTYP .
      CLEAR /PTLOMS/V009-TXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V009 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V009-AUART TO
/PTLOMS/TB010-AUART .
MOVE /PTLOMS/V009-MANDT TO
/PTLOMS/TB010-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB010'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB010 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB010'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V009 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB010-MANDT =
/PTLOMS/V009-MANDT .
/PTLOMS/TB010-AUART =
/PTLOMS/V009-AUART .
    SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
    IF SY-SUBRC EQ 0.
/PTLOMS/V009-AUTYP =
T003O-AUTYP .
      SELECT SINGLE * FROM T003P WHERE
AUART = T003O-AUART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V009-TXT =
T003P-TXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V009-TXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V009-AUTYP .
      CLEAR /PTLOMS/V009-TXT .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V010....................................*
FORM GET_DATA_/PTLOMS/V010.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB011 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V010 .
/PTLOMS/V010-MANDT =
/PTLOMS/TB011-MANDT .
/PTLOMS/V010-MTART =
/PTLOMS/TB011-MTART .
    SELECT SINGLE * FROM T134 WHERE
MTART = /PTLOMS/TB011-MTART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T134T WHERE
MTART = T134-MTART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V010-MTBEZ =
T134T-MTBEZ .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V010.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V010 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V010.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V010-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB011 WHERE
  MTART = /PTLOMS/V010-MTART .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB011 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB011 WHERE
  MTART = /PTLOMS/V010-MTART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB011.
    ENDIF.
/PTLOMS/TB011-MANDT =
/PTLOMS/V010-MANDT .
/PTLOMS/TB011-MTART =
/PTLOMS/V010-MTART .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB011 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB011 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V010-UPD_FLAG,
STATUS_/PTLOMS/V010-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V010.
  SELECT SINGLE * FROM /PTLOMS/TB011 WHERE
MTART = /PTLOMS/V010-MTART .
/PTLOMS/V010-MANDT =
/PTLOMS/TB011-MANDT .
/PTLOMS/V010-MTART =
/PTLOMS/TB011-MTART .
    SELECT SINGLE * FROM T134 WHERE
MTART = /PTLOMS/TB011-MTART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T134T WHERE
MTART = T134-MTART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V010-MTBEZ =
T134T-MTBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V010-MTBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V010-MTBEZ .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V010 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V010-MTART TO
/PTLOMS/TB011-MTART .
MOVE /PTLOMS/V010-MANDT TO
/PTLOMS/TB011-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB011'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB011 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB011'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V010 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB011-MANDT =
/PTLOMS/V010-MANDT .
/PTLOMS/TB011-MTART =
/PTLOMS/V010-MTART .
    SELECT SINGLE * FROM T134 WHERE
MTART = /PTLOMS/TB011-MTART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T134T WHERE
MTART = T134-MTART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V010-MTBEZ =
T134T-MTBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V010-MTBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V010-MTBEZ .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V011....................................*
FORM GET_DATA_/PTLOMS/V011.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB024 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V011 .
/PTLOMS/V011-MANDT =
/PTLOMS/TB024-MANDT .
/PTLOMS/V011-ILART =
/PTLOMS/TB024-ILART .
    SELECT SINGLE * FROM T353I WHERE
ILART = /PTLOMS/TB024-ILART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T353I_T WHERE
ILART = T353I-ILART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V011-ILATX =
T353I_T-ILATX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V011.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V011 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V011.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V011-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB024 WHERE
  ILART = /PTLOMS/V011-ILART .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB024 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB024 WHERE
  ILART = /PTLOMS/V011-ILART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB024.
    ENDIF.
/PTLOMS/TB024-MANDT =
/PTLOMS/V011-MANDT .
/PTLOMS/TB024-ILART =
/PTLOMS/V011-ILART .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB024 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB024 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V011-UPD_FLAG,
STATUS_/PTLOMS/V011-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V011.
  SELECT SINGLE * FROM /PTLOMS/TB024 WHERE
ILART = /PTLOMS/V011-ILART .
/PTLOMS/V011-MANDT =
/PTLOMS/TB024-MANDT .
/PTLOMS/V011-ILART =
/PTLOMS/TB024-ILART .
    SELECT SINGLE * FROM T353I WHERE
ILART = /PTLOMS/TB024-ILART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T353I_T WHERE
ILART = T353I-ILART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V011-ILATX =
T353I_T-ILATX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V011-ILATX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V011-ILATX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V011 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V011-ILART TO
/PTLOMS/TB024-ILART .
MOVE /PTLOMS/V011-MANDT TO
/PTLOMS/TB024-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB024'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB024 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB024'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V011 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB024-MANDT =
/PTLOMS/V011-MANDT .
/PTLOMS/TB024-ILART =
/PTLOMS/V011-ILART .
    SELECT SINGLE * FROM T353I WHERE
ILART = /PTLOMS/TB024-ILART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T353I_T WHERE
ILART = T353I-ILART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V011-ILATX =
T353I_T-ILATX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V011-ILATX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V011-ILATX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V012....................................*
FORM GET_DATA_/PTLOMS/V012.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB027 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V012 .
/PTLOMS/V012-MANDT =
/PTLOMS/TB027-MANDT .
/PTLOMS/V012-MATKL =
/PTLOMS/TB027-MATKL .
    SELECT SINGLE * FROM T023 WHERE
MATKL = /PTLOMS/TB027-MATKL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T023T WHERE
MATKL = T023-MATKL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V012-WGBEZ =
T023T-WGBEZ .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V012.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V012 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V012.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V012-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB027 WHERE
  MATKL = /PTLOMS/V012-MATKL .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB027 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB027 WHERE
  MATKL = /PTLOMS/V012-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB027.
    ENDIF.
/PTLOMS/TB027-MANDT =
/PTLOMS/V012-MANDT .
/PTLOMS/TB027-MATKL =
/PTLOMS/V012-MATKL .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB027 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB027 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V012-UPD_FLAG,
STATUS_/PTLOMS/V012-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V012.
  SELECT SINGLE * FROM /PTLOMS/TB027 WHERE
MATKL = /PTLOMS/V012-MATKL .
/PTLOMS/V012-MANDT =
/PTLOMS/TB027-MANDT .
/PTLOMS/V012-MATKL =
/PTLOMS/TB027-MATKL .
    SELECT SINGLE * FROM T023 WHERE
MATKL = /PTLOMS/TB027-MATKL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T023T WHERE
MATKL = T023-MATKL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V012-WGBEZ =
T023T-WGBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V012-WGBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V012-WGBEZ .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V012 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V012-MATKL TO
/PTLOMS/TB027-MATKL .
MOVE /PTLOMS/V012-MANDT TO
/PTLOMS/TB027-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB027'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB027 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB027'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V012 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB027-MANDT =
/PTLOMS/V012-MANDT .
/PTLOMS/TB027-MATKL =
/PTLOMS/V012-MATKL .
    SELECT SINGLE * FROM T023 WHERE
MATKL = /PTLOMS/TB027-MATKL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T023T WHERE
MATKL = T023-MATKL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V012-WGBEZ =
T023T-WGBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V012-WGBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V012-WGBEZ .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V013....................................*
FORM GET_DATA_/PTLOMS/V013.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB029 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V013 .
/PTLOMS/V013-MANDT =
/PTLOMS/TB029-MANDT .
/PTLOMS/V013-WERKS =
/PTLOMS/TB029-WERKS .
/PTLOMS/V013-LGORT =
/PTLOMS/TB029-LGORT .
    SELECT SINGLE * FROM T001L WHERE
WERKS = /PTLOMS/TB029-WERKS AND
LGORT = /PTLOMS/TB029-LGORT .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-LGOBE =
T001L-LGOBE .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB029-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V013.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V013 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V013.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V013-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB029 WHERE
  WERKS = /PTLOMS/V013-WERKS AND
  LGORT = /PTLOMS/V013-LGORT .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB029 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB029 WHERE
  WERKS = /PTLOMS/V013-WERKS AND
  LGORT = /PTLOMS/V013-LGORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB029.
    ENDIF.
/PTLOMS/TB029-MANDT =
/PTLOMS/V013-MANDT .
/PTLOMS/TB029-WERKS =
/PTLOMS/V013-WERKS .
/PTLOMS/TB029-LGORT =
/PTLOMS/V013-LGORT .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB029 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB029 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V013-UPD_FLAG,
STATUS_/PTLOMS/V013-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V013.
  SELECT SINGLE * FROM /PTLOMS/TB029 WHERE
WERKS = /PTLOMS/V013-WERKS AND
LGORT = /PTLOMS/V013-LGORT .
/PTLOMS/V013-MANDT =
/PTLOMS/TB029-MANDT .
/PTLOMS/V013-WERKS =
/PTLOMS/TB029-WERKS .
/PTLOMS/V013-LGORT =
/PTLOMS/TB029-LGORT .
    SELECT SINGLE * FROM T001L WHERE
WERKS = /PTLOMS/TB029-WERKS AND
LGORT = /PTLOMS/TB029-LGORT .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-LGOBE =
T001L-LGOBE .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V013-LGOBE .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB029-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V013-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V013 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V013-WERKS TO
/PTLOMS/TB029-WERKS .
MOVE /PTLOMS/V013-LGORT TO
/PTLOMS/TB029-LGORT .
MOVE /PTLOMS/V013-MANDT TO
/PTLOMS/TB029-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB029'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB029 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB029'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V013 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB029-MANDT =
/PTLOMS/V013-MANDT .
/PTLOMS/TB029-WERKS =
/PTLOMS/V013-WERKS .
/PTLOMS/TB029-LGORT =
/PTLOMS/V013-LGORT .
    SELECT SINGLE * FROM T001L WHERE
WERKS = /PTLOMS/TB029-WERKS AND
LGORT = /PTLOMS/TB029-LGORT .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-LGOBE =
T001L-LGOBE .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V013-LGOBE .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB029-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V013-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V013-NAME1 .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V015....................................*
FORM GET_DATA_/PTLOMS/V015.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB034 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V015 .
/PTLOMS/V015-MANDT =
/PTLOMS/TB034-MANDT .
/PTLOMS/V015-AUART =
/PTLOMS/TB034-AUART .
/PTLOMS/V015-ARTPR =
/PTLOMS/TB034-ARTPR .
/PTLOMS/V015-PRIOK =
/PTLOMS/TB034-PRIOK .
/PTLOMS/V015-URGENTE =
/PTLOMS/TB034-URGENTE .
/PTLOMS/V015-VERDE =
/PTLOMS/TB034-VERDE .
/PTLOMS/V015-AMARELO =
/PTLOMS/TB034-AMARELO .
/PTLOMS/V015-VERMELHO =
/PTLOMS/TB034-VERMELHO .
    SELECT SINGLE * FROM /PTLOMS/TB010 WHERE
AUART = /PTLOMS/TB034-AUART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T350 WHERE
AUART = T003O-AUART .
        IF SY-SUBRC EQ 0.
        ENDIF.
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM T356 WHERE
ARTPR = /PTLOMS/TB034-ARTPR AND
PRIOK = /PTLOMS/TB034-PRIOK .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T356_T WHERE
ARTPR = T356-ARTPR AND
PRIOK = T356-PRIOK AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V015-PRIOKX =
T356_T-PRIOKX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V015.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V015 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V015.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V015-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB034 WHERE
  AUART = /PTLOMS/V015-AUART AND
  PRIOK = /PTLOMS/V015-PRIOK AND
  ARTPR = /PTLOMS/V015-ARTPR .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB034 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB034 WHERE
  AUART = /PTLOMS/V015-AUART AND
  PRIOK = /PTLOMS/V015-PRIOK AND
  ARTPR = /PTLOMS/V015-ARTPR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB034.
    ENDIF.
/PTLOMS/TB034-MANDT =
/PTLOMS/V015-MANDT .
/PTLOMS/TB034-AUART =
/PTLOMS/V015-AUART .
/PTLOMS/TB034-ARTPR =
/PTLOMS/V015-ARTPR .
/PTLOMS/TB034-PRIOK =
/PTLOMS/V015-PRIOK .
/PTLOMS/TB034-URGENTE =
/PTLOMS/V015-URGENTE .
/PTLOMS/TB034-VERDE =
/PTLOMS/V015-VERDE .
/PTLOMS/TB034-AMARELO =
/PTLOMS/V015-AMARELO .
/PTLOMS/TB034-VERMELHO =
/PTLOMS/V015-VERMELHO .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB034 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB034 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V015-UPD_FLAG,
STATUS_/PTLOMS/V015-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V015.
  SELECT SINGLE * FROM /PTLOMS/TB034 WHERE
AUART = /PTLOMS/V015-AUART AND
PRIOK = /PTLOMS/V015-PRIOK AND
ARTPR = /PTLOMS/V015-ARTPR .
/PTLOMS/V015-MANDT =
/PTLOMS/TB034-MANDT .
/PTLOMS/V015-AUART =
/PTLOMS/TB034-AUART .
/PTLOMS/V015-ARTPR =
/PTLOMS/TB034-ARTPR .
/PTLOMS/V015-PRIOK =
/PTLOMS/TB034-PRIOK .
/PTLOMS/V015-URGENTE =
/PTLOMS/TB034-URGENTE .
/PTLOMS/V015-VERDE =
/PTLOMS/TB034-VERDE .
/PTLOMS/V015-AMARELO =
/PTLOMS/TB034-AMARELO .
/PTLOMS/V015-VERMELHO =
/PTLOMS/TB034-VERMELHO .
    SELECT SINGLE * FROM /PTLOMS/TB010 WHERE
AUART = /PTLOMS/TB034-AUART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T350 WHERE
AUART = T003O-AUART .
        IF SY-SUBRC EQ 0.
        ELSE.
          CLEAR SY-SUBRC.
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T356 WHERE
ARTPR = /PTLOMS/TB034-ARTPR AND
PRIOK = /PTLOMS/TB034-PRIOK .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T356_T WHERE
ARTPR = T356-ARTPR AND
PRIOK = T356-PRIOK AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V015-PRIOKX =
T356_T-PRIOKX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V015-PRIOKX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V015-PRIOKX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V015 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V015-AUART TO
/PTLOMS/TB034-AUART .
MOVE /PTLOMS/V015-PRIOK TO
/PTLOMS/TB034-PRIOK .
MOVE /PTLOMS/V015-ARTPR TO
/PTLOMS/TB034-ARTPR .
MOVE /PTLOMS/V015-MANDT TO
/PTLOMS/TB034-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB034'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB034 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB034'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V015 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB034-MANDT =
/PTLOMS/V015-MANDT .
/PTLOMS/TB034-AUART =
/PTLOMS/V015-AUART .
/PTLOMS/TB034-ARTPR =
/PTLOMS/V015-ARTPR .
/PTLOMS/TB034-PRIOK =
/PTLOMS/V015-PRIOK .
/PTLOMS/TB034-URGENTE =
/PTLOMS/V015-URGENTE .
/PTLOMS/TB034-VERDE =
/PTLOMS/V015-VERDE .
/PTLOMS/TB034-AMARELO =
/PTLOMS/V015-AMARELO .
/PTLOMS/TB034-VERMELHO =
/PTLOMS/V015-VERMELHO .
    SELECT SINGLE * FROM /PTLOMS/TB010 WHERE
AUART = /PTLOMS/TB034-AUART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003O WHERE
AUART = /PTLOMS/TB010-AUART .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T350 WHERE
AUART = T003O-AUART .
        IF SY-SUBRC EQ 0.
        ELSE.
          CLEAR SY-SUBRC.
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T356 WHERE
ARTPR = /PTLOMS/TB034-ARTPR AND
PRIOK = /PTLOMS/TB034-PRIOK .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T356_T WHERE
ARTPR = T356-ARTPR AND
PRIOK = T356-PRIOK AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V015-PRIOKX =
T356_T-PRIOKX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V015-PRIOKX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V015-PRIOKX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V016....................................*
FORM GET_DATA_/PTLOMS/V016.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB038 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V016 .
/PTLOMS/V016-MANDT =
/PTLOMS/TB038-MANDT .
/PTLOMS/V016-WERKS =
/PTLOMS/TB038-WERKS .
/PTLOMS/V016-GRUND =
/PTLOMS/TB038-GRUND .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB038-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V016-NAME1 =
T001W-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = /PTLOMS/TB038-WERKS AND
GRUND = /PTLOMS/TB038-GRUND .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V016-GRDTX =
TRUGT-GRDTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V016.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V016 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V016.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V016-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB038 WHERE
  WERKS = /PTLOMS/V016-WERKS AND
  GRUND = /PTLOMS/V016-GRUND .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB038 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB038 WHERE
  WERKS = /PTLOMS/V016-WERKS AND
  GRUND = /PTLOMS/V016-GRUND .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB038.
    ENDIF.
/PTLOMS/TB038-MANDT =
/PTLOMS/V016-MANDT .
/PTLOMS/TB038-WERKS =
/PTLOMS/V016-WERKS .
/PTLOMS/TB038-GRUND =
/PTLOMS/V016-GRUND .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB038 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB038 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V016-UPD_FLAG,
STATUS_/PTLOMS/V016-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V016.
  SELECT SINGLE * FROM /PTLOMS/TB038 WHERE
WERKS = /PTLOMS/V016-WERKS AND
GRUND = /PTLOMS/V016-GRUND .
/PTLOMS/V016-MANDT =
/PTLOMS/TB038-MANDT .
/PTLOMS/V016-WERKS =
/PTLOMS/TB038-WERKS .
/PTLOMS/V016-GRUND =
/PTLOMS/TB038-GRUND .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB038-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V016-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V016-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = /PTLOMS/TB038-WERKS AND
GRUND = /PTLOMS/TB038-GRUND .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V016-GRDTX =
TRUGT-GRDTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V016-GRDTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V016-GRDTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V016 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V016-WERKS TO
/PTLOMS/TB038-WERKS .
MOVE /PTLOMS/V016-GRUND TO
/PTLOMS/TB038-GRUND .
MOVE /PTLOMS/V016-MANDT TO
/PTLOMS/TB038-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB038'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB038 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB038'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V016 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB038-MANDT =
/PTLOMS/V016-MANDT .
/PTLOMS/TB038-WERKS =
/PTLOMS/V016-WERKS .
/PTLOMS/TB038-GRUND =
/PTLOMS/V016-GRUND .
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB038-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V016-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V016-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = /PTLOMS/TB038-WERKS AND
GRUND = /PTLOMS/TB038-GRUND .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V016-GRDTX =
TRUGT-GRDTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V016-GRDTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V016-GRDTX .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V017....................................*
FORM GET_DATA_/PTLOMS/V017.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB045 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V017 .
/PTLOMS/V017-MANDT =
/PTLOMS/TB045-MANDT .
/PTLOMS/V017-WERKS =
/PTLOMS/TB045-WERKS .
/PTLOMS/V017-TPLNR =
/PTLOMS/TB045-TPLNR .
    SELECT SINGLE * FROM IFLOT WHERE
TPLNR = /PTLOMS/TB045-TPLNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM IFLOTX WHERE
TPLNR = IFLOT-TPLNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V017-PLTXT =
IFLOTX-PLTXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB045-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V017-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V017.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V017 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V017.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V017-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB045 WHERE
  WERKS = /PTLOMS/V017-WERKS AND
  TPLNR = /PTLOMS/V017-TPLNR .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB045 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB045 WHERE
  WERKS = /PTLOMS/V017-WERKS AND
  TPLNR = /PTLOMS/V017-TPLNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB045.
    ENDIF.
/PTLOMS/TB045-MANDT =
/PTLOMS/V017-MANDT .
/PTLOMS/TB045-WERKS =
/PTLOMS/V017-WERKS .
/PTLOMS/TB045-TPLNR =
/PTLOMS/V017-TPLNR .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB045 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB045 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V017-UPD_FLAG,
STATUS_/PTLOMS/V017-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V017.
  SELECT SINGLE * FROM /PTLOMS/TB045 WHERE
WERKS = /PTLOMS/V017-WERKS AND
TPLNR = /PTLOMS/V017-TPLNR .
/PTLOMS/V017-MANDT =
/PTLOMS/TB045-MANDT .
/PTLOMS/V017-WERKS =
/PTLOMS/TB045-WERKS .
/PTLOMS/V017-TPLNR =
/PTLOMS/TB045-TPLNR .
    SELECT SINGLE * FROM IFLOT WHERE
TPLNR = /PTLOMS/TB045-TPLNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM IFLOTX WHERE
TPLNR = IFLOT-TPLNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V017-PLTXT =
IFLOTX-PLTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V017-PLTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V017-PLTXT .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB045-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V017-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V017-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V017 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V017-WERKS TO
/PTLOMS/TB045-WERKS .
MOVE /PTLOMS/V017-TPLNR TO
/PTLOMS/TB045-TPLNR .
MOVE /PTLOMS/V017-MANDT TO
/PTLOMS/TB045-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB045'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB045 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB045'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V017 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB045-MANDT =
/PTLOMS/V017-MANDT .
/PTLOMS/TB045-WERKS =
/PTLOMS/V017-WERKS .
/PTLOMS/TB045-TPLNR =
/PTLOMS/V017-TPLNR .
    SELECT SINGLE * FROM IFLOT WHERE
TPLNR = /PTLOMS/TB045-TPLNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM IFLOTX WHERE
TPLNR = IFLOT-TPLNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V017-PLTXT =
IFLOTX-PLTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V017-PLTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V017-PLTXT .
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB045-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V017-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V017-NAME1 .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V018....................................*
FORM GET_DATA_/PTLOMS/V018.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB005 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V018 .
/PTLOMS/V018-MANDT =
/PTLOMS/TB005-MANDT .
/PTLOMS/V018-OBJID =
/PTLOMS/TB005-OBJID .
/PTLOMS/V018-ARBPL =
/PTLOMS/TB005-ARBPL .
/PTLOMS/V018-WERKS =
/PTLOMS/TB005-WERKS .
/PTLOMS/V018-LEARR =
/PTLOMS/TB005-LEARR .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V018-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /PTLOMS/V018.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V018 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V018.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V018-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB005 WHERE
  OBJID = /PTLOMS/V018-OBJID .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB005 WHERE
  OBJID = /PTLOMS/V018-OBJID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB005.
    ENDIF.
/PTLOMS/TB005-MANDT =
/PTLOMS/V018-MANDT .
/PTLOMS/TB005-OBJID =
/PTLOMS/V018-OBJID .
/PTLOMS/TB005-ARBPL =
/PTLOMS/V018-ARBPL .
/PTLOMS/TB005-WERKS =
/PTLOMS/V018-WERKS .
/PTLOMS/TB005-LEARR =
/PTLOMS/V018-LEARR .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB005 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V018-UPD_FLAG,
STATUS_/PTLOMS/V018-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V018.
  SELECT SINGLE * FROM /PTLOMS/TB005 WHERE
OBJID = /PTLOMS/V018-OBJID .
/PTLOMS/V018-MANDT =
/PTLOMS/TB005-MANDT .
/PTLOMS/V018-OBJID =
/PTLOMS/TB005-OBJID .
/PTLOMS/V018-ARBPL =
/PTLOMS/TB005-ARBPL .
/PTLOMS/V018-WERKS =
/PTLOMS/TB005-WERKS .
/PTLOMS/V018-LEARR =
/PTLOMS/TB005-LEARR .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V018-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V018-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V018 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V018-OBJID TO
/PTLOMS/TB005-OBJID .
MOVE /PTLOMS/V018-MANDT TO
/PTLOMS/TB005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V018 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB005-MANDT =
/PTLOMS/V018-MANDT .
/PTLOMS/TB005-OBJID =
/PTLOMS/V018-OBJID .
/PTLOMS/TB005-ARBPL =
/PTLOMS/V018-ARBPL .
/PTLOMS/TB005-WERKS =
/PTLOMS/V018-WERKS .
/PTLOMS/TB005-LEARR =
/PTLOMS/V018-LEARR .
    SELECT * FROM CRHD WHERE
OBJID = /PTLOMS/TB005-OBJID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM T001W WHERE
WERKS = /PTLOMS/TB005-WERKS .
    IF SY-SUBRC EQ 0.
/PTLOMS/V018-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V018-NAME1 .
    ENDIF.
ENDFORM.
*...processing: /PTLOMS/V020....................................*
FORM GET_DATA_/PTLOMS/V020.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /PTLOMS/TB058 WHERE
(VIM_WHERETAB) .
    CLEAR /PTLOMS/V020 .
/PTLOMS/V020-MANDT =
/PTLOMS/TB058-MANDT .
/PTLOMS/V020-ATNAM =
/PTLOMS/TB058-ATNAM .
/PTLOMS/V020-ATINN =
/PTLOMS/TB058-ATINN .
    SELECT * FROM CABN WHERE
ATINN = /PTLOMS/TB058-ATINN .
      SELECT SINGLE * FROM CABNT WHERE
ATINN = CABN-ATINN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V020-ATBEZ =
CABNT-ATBEZ .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = /PTLOMS/V020.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/PTLOMS/V020 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /PTLOMS/V020.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/PTLOMS/V020-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB058 WHERE
  ATNAM = /PTLOMS/V020-ATNAM .
    IF SY-SUBRC = 0.
    DELETE /PTLOMS/TB058 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /PTLOMS/TB058 WHERE
  ATNAM = /PTLOMS/V020-ATNAM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /PTLOMS/TB058.
    ENDIF.
/PTLOMS/TB058-MANDT =
/PTLOMS/V020-MANDT .
/PTLOMS/TB058-ATNAM =
/PTLOMS/V020-ATNAM .
/PTLOMS/TB058-ATINN =
/PTLOMS/V020-ATINN .
    IF SY-SUBRC = 0.
    UPDATE /PTLOMS/TB058 ##WARN_OK.
    ELSE.
    INSERT /PTLOMS/TB058 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/PTLOMS/V020-UPD_FLAG,
STATUS_/PTLOMS/V020-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/PTLOMS/V020.
  SELECT SINGLE * FROM /PTLOMS/TB058 WHERE
ATNAM = /PTLOMS/V020-ATNAM .
/PTLOMS/V020-MANDT =
/PTLOMS/TB058-MANDT .
/PTLOMS/V020-ATNAM =
/PTLOMS/TB058-ATNAM .
/PTLOMS/V020-ATINN =
/PTLOMS/TB058-ATINN .
    SELECT * FROM CABN WHERE
ATINN = /PTLOMS/TB058-ATINN .
      SELECT SINGLE * FROM CABNT WHERE
ATINN = CABN-ATINN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V020-ATBEZ =
CABNT-ATBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V020-ATBEZ .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V020-ATBEZ .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/PTLOMS/V020 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /PTLOMS/V020-ATNAM TO
/PTLOMS/TB058-ATNAM .
MOVE /PTLOMS/V020-MANDT TO
/PTLOMS/TB058-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/PTLOMS/TB058'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /PTLOMS/TB058 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/PTLOMS/TB058'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/PTLOMS/V020 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/PTLOMS/TB058-MANDT =
/PTLOMS/V020-MANDT .
/PTLOMS/TB058-ATNAM =
/PTLOMS/V020-ATNAM .
/PTLOMS/TB058-ATINN =
/PTLOMS/V020-ATINN .
    SELECT * FROM CABN WHERE
ATINN = /PTLOMS/TB058-ATINN .
      SELECT SINGLE * FROM CABNT WHERE
ATINN = CABN-ATINN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/PTLOMS/V020-ATBEZ =
CABNT-ATBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /PTLOMS/V020-ATBEZ .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR /PTLOMS/V020-ATBEZ .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
