PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB070 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE z_desc_aplicacao.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB070-APLICACAO .
    FIELD /PTLOMS/TB070-FORMULARIO .
    FIELD /PTLOMS/TB070-DESCRICAO .
    FIELD /PTLOMS/TB070-ERNAM .
    FIELD /PTLOMS/TB070-ERDAT .
    FIELD /PTLOMS/TB070-ERZEIT .
    FIELD /PTLOMS/TB070-AENAM .
    FIELD /PTLOMS/TB070-AEDAT .
    FIELD /PTLOMS/TB070-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB070-APLICACAO .
    FIELD /PTLOMS/TB070-FORMULARIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
