PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB026 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB026-AUFNR .
    FIELD /PTLOMS/TB026-VORNR .
    FIELD /PTLOMS/TB026-SUBOPER .
    FIELD /PTLOMS/TB026-USUARIO .
    FIELD /PTLOMS/TB026-DATA_ASSOCIACAO .
    FIELD /PTLOMS/TB026-HORA_ASSOCIACAO .
    FIELD /PTLOMS/TB026-DATA_DESASSOCIACAO .
    FIELD /PTLOMS/TB026-HORA_DESASSOCIACAO .
    FIELD /PTLOMS/TB026-MOTIVO_DESASSOCIACAO .
    FIELD /PTLOMS/TB026-DESASSOCIADO .
    FIELD /PTLOMS/TB026-MOBILE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB026-AUFNR .
    FIELD /PTLOMS/TB026-VORNR .
    FIELD /PTLOMS/TB026-SUBOPER .
    FIELD /PTLOMS/TB026-USUARIO .
    FIELD /PTLOMS/TB026-DATA_ASSOCIACAO .
    FIELD /PTLOMS/TB026-HORA_ASSOCIACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
