PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB042 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB042-CHAVE .
    FIELD /PTLOMS/TB042-CONF_NO_REFE .
    FIELD /PTLOMS/TB042-CONF_CNT_REFE .
    FIELD /PTLOMS/TB042-CONF_NO .
    FIELD /PTLOMS/TB042-CONF_CNT .
    FIELD /PTLOMS/TB042-AUFNR .
    FIELD /PTLOMS/TB042-VORNR .
    FIELD /PTLOMS/TB042-STATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB042-CHAVE .
    FIELD /PTLOMS/TB042-CONF_NO_REFE .
    FIELD /PTLOMS/TB042-CONF_CNT_REFE .
    FIELD /PTLOMS/TB042-CONF_NO .
    FIELD /PTLOMS/TB042-CONF_CNT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
