PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB088 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB088-CRITIC_ID .
    FIELD /PTLOMS/TB088-DESCRICAO .
    FIELD /PTLOMS/TB088-PESO .
    FIELD /PTLOMS/TB088-ERNAM .
    FIELD /PTLOMS/TB088-ERDAT .
    FIELD /PTLOMS/TB088-ERZEIT .
    FIELD /PTLOMS/TB088-AENAM .
    FIELD /PTLOMS/TB088-AEDAT .
    FIELD /PTLOMS/TB088-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB088-CRITIC_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
