PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB085 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB085-REGIAO_ID .
    FIELD /PTLOMS/TB085-DESCRICAO .
    FIELD /PTLOMS/TB085-BAIRRO .
    FIELD /PTLOMS/TB085-ZONA .
    FIELD /PTLOMS/TB085-CIDADE .
    FIELD /PTLOMS/TB085-ESTADO .
    FIELD /PTLOMS/TB085-PAIS .
    FIELD /PTLOMS/TB085-TIPO_ATEND .
    FIELD /PTLOMS/TB085-ERNAM .
    FIELD /PTLOMS/TB085-ERDAT .
    FIELD /PTLOMS/TB085-ERZEIT .
    FIELD /PTLOMS/TB085-AENAM .
    FIELD /PTLOMS/TB085-AEDAT .
    FIELD /PTLOMS/TB085-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB085-REGIAO_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
