PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB103 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB103-TIPO_OBJETO .
    FIELD /PTLOMS/TB103-OBJETO .
    FIELD /PTLOMS/TB103-TIPO_EVENTO .
    FIELD /PTLOMS/TB103-ID_LISTA .
    FIELD /PTLOMS/TB103-EMAIL .
    FIELD /PTLOMS/TB103-WHATSAPP .
    FIELD /PTLOMS/TB103-ATIVO .
    FIELD /PTLOMS/TB103-ERNAM .
    FIELD /PTLOMS/TB103-ERDAT .
    FIELD /PTLOMS/TB103-ERZEIT .
    FIELD /PTLOMS/TB103-AENAM .
    FIELD /PTLOMS/TB103-AEDAT .
    FIELD /PTLOMS/TB103-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB103-TIPO_OBJETO .
    FIELD /PTLOMS/TB103-OBJETO .
    FIELD /PTLOMS/TB103-TIPO_EVENTO .
    FIELD /PTLOMS/TB103-ID_LISTA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
