PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB086 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB086-CERT_ID .
    FIELD /PTLOMS/TB086-DESCRICAO .
    FIELD /PTLOMS/TB086-VALIDADE_OBRIG .
    FIELD /PTLOMS/TB086-ERNAM .
    FIELD /PTLOMS/TB086-ERDAT .
    FIELD /PTLOMS/TB086-ERZEIT .
    FIELD /PTLOMS/TB086-AENAM .
    FIELD /PTLOMS/TB086-AEDAT .
    FIELD /PTLOMS/TB086-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB086-CERT_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
