PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB075 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE z_busca_descricoes.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB075-APLICACAO .
    FIELD /PTLOMS/TB075-FORMULARIO .
    FIELD /PTLOMS/TB075-SEQUENCIAL .
    FIELD /PTLOMS/TB075-ORDENACAO1 .
    FIELD /PTLOMS/TB075-ORDENACAO2 .
    FIELD /PTLOMS/TB075-DESCRICAO .
    FIELD /PTLOMS/TB075-RESPOSTA .
    FIELD /PTLOMS/TB075-OPCAO .
    FIELD /PTLOMS/TB075-GRUPO .
    FIELD /PTLOMS/TB075-OBRIGATORIO .
    FIELD /PTLOMS/TB075-INF_COMPLEMENTAR .
    FIELD /PTLOMS/TB075-ERNAM .
    FIELD /PTLOMS/TB075-ERDAT .
    FIELD /PTLOMS/TB075-ERZEIT .
    FIELD /PTLOMS/TB075-AENAM .
    FIELD /PTLOMS/TB075-AEDAT .
    FIELD /PTLOMS/TB075-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB075-APLICACAO .
    FIELD /PTLOMS/TB075-FORMULARIO .
    FIELD /PTLOMS/TB075-SEQUENCIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
