PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB102 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB102-ID_LISTA .
    FIELD /PTLOMS/TB102-USUARIO .
    FIELD /PTLOMS/TB102-ERNAM .
    FIELD /PTLOMS/TB102-ERDAT .
    FIELD /PTLOMS/TB102-ERZEIT .
    FIELD /PTLOMS/TB102-AENAM .
    FIELD /PTLOMS/TB102-AEDAT .
    FIELD /PTLOMS/TB102-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB102-ID_LISTA .
    FIELD /PTLOMS/TB102-USUARIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
