PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB200 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB200-PRODUCT_ID .
    FIELD /PTLOMS/TB200-DESCRIPTION .
    FIELD /PTLOMS/TB200-ACTIVE .
    FIELD /PTLOMS/TB200-SSF_SIGN_APP .
    FIELD /PTLOMS/TB200-SSF_VERIFY_APP .
    FIELD /PTLOMS/TB200-INSTALLED_BY .
    FIELD /PTLOMS/TB200-INSTALLED_ON .
    FIELD /PTLOMS/TB200-INSTALLED_AT .
    FIELD /PTLOMS/TB200-CHANGED_BY .
    FIELD /PTLOMS/TB200-CHANGED_ON .
    FIELD /PTLOMS/TB200-CHANGED_AT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB200-PRODUCT_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
