PROCESS BEFORE OUTPUT.

  MODULE cria_objeto_oms.

*  MODULE get_componente_mem.

  MODULE pbo_005.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL '/PTLOMS/TC001'
  MODULE /PTLOMS/TC001_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE /PTLOMS/TC001_CHANGE_COL_ATTR.
  LOOP AT   LT_ALERTS
       INTO LS_ALERT
       WITH CONTROL /PTLOMS/TC001
       CURSOR /PTLOMS/TC001-CURRENT_LINE.
*&SPWIZARD:   MODULE /PTLOMS/TC001_CHANGE_FIELD_ATTR
  ENDLOOP.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL '/PTLOMS/TC001'
  LOOP AT LT_ALERTS.
    CHAIN.
      FIELD LS_ALERT-WERKS.
*      FIELD LS_ALERT-LICENSE_ID.
      FIELD LS_ALERT-VALID_TO.
      FIELD LS_ALERT-DAYS_REMAINING.
      FIELD LS_ALERT-STATUS.
      FIELD LS_ALERT-MESSAGE.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE /PTLOMS/TC001_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE /PTLOMS/TC001_CHANGE_COL_ATTR.

* Procedimentos a serem executados na saída
  MODULE saida AT EXIT-COMMAND.

  MODULE user_command_0005.
