PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB084 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB084-SKILL_ID .
    FIELD /PTLOMS/TB084-DESCRICAO.
    FIELD /PTLOMS/TB084-ATIVO .
    FIELD /PTLOMS/TB084-ERNAM.
    FIELD /PTLOMS/TB084-ERDAT .
    FIELD /PTLOMS/TB084-ERZEIT .
    FIELD /PTLOMS/TB084-AENAM. " MODULE z_control_fields_0100.
    FIELD /PTLOMS/TB084-AEDAT .
    FIELD /PTLOMS/TB084-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB084-SKILL_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
