PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB079 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB079-USUARIO .
    FIELD /PTLOMS/TB079-MATRICULA .
    FIELD /PTLOMS/TB079-GUID .
    FIELD /PTLOMS/TB079-PERFIL .
    FIELD /PTLOMS/TB079-LATITUDE .
    FIELD /PTLOMS/TB079-LONGITUDE .
    FIELD /PTLOMS/TB079-EVENTO .
    FIELD /PTLOMS/TB079-DATA_COLETA .
    FIELD /PTLOMS/TB079-HORA_COLETA .
    FIELD /PTLOMS/TB079-DATA_CRIACAO .
    FIELD /PTLOMS/TB079-HORA_CRIACAO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB079-USUARIO .
    FIELD /PTLOMS/TB079-MATRICULA .
    FIELD /PTLOMS/TB079-GUID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
