PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB031 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB031-AUFNR .
    FIELD /PTLOMS/TB031-VORNR .
    FIELD /PTLOMS/TB031-SUBOPER .
    FIELD /PTLOMS/TB031-USUARIO .
    FIELD /PTLOMS/TB031-DATA_INI .
    FIELD /PTLOMS/TB031-HORA_INI .
    FIELD /PTLOMS/TB031-DATA_FIM .
    FIELD /PTLOMS/TB031-HORA_FIM .
    FIELD /PTLOMS/TB031-STATUS .
    FIELD /PTLOMS/TB031-DATA_INATIVACAO .
    FIELD /PTLOMS/TB031-HORA_INATIVACAO .
    FIELD /PTLOMS/TB031-INATIVO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB031-AUFNR .
    FIELD /PTLOMS/TB031-VORNR .
    FIELD /PTLOMS/TB031-SUBOPER .
    FIELD /PTLOMS/TB031-USUARIO .
    FIELD /PTLOMS/TB031-DATA_INI .
    FIELD /PTLOMS/TB031-HORA_INI .
    FIELD /PTLOMS/TB031-DATA_FIM .
    FIELD /PTLOMS/TB031-HORA_FIM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
