PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB105 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB105-ID_NOTIFICACAO .
    FIELD /PTLOMS/TB105-USUARIO .
    FIELD /PTLOMS/TB105-EMAIL .
    FIELD /PTLOMS/TB105-TELEFONE .
    FIELD /PTLOMS/TB105-LIDO .
    FIELD /PTLOMS/TB105-DATA_LEITURA .
    FIELD /PTLOMS/TB105-HORA_LEITURA .
    FIELD /PTLOMS/TB105-STATUS_EMAIL .
    FIELD /PTLOMS/TB105-TENT_EMAIL .
    FIELD /PTLOMS/TB105-ERRO_EMAIL .
    FIELD /PTLOMS/TB105-DATA_EMAIL .
    FIELD /PTLOMS/TB105-HORA_EMAIL .
    FIELD /PTLOMS/TB105-STATUS_WHATS .
    FIELD /PTLOMS/TB105-TENT_WHATS .
    FIELD /PTLOMS/TB105-DATA_WHATS .
    FIELD /PTLOMS/TB105-HORA_WHATS .
    FIELD /PTLOMS/TB105-ERRO_WHATS .
    FIELD /PTLOMS/TB105-ERNAM .
    FIELD /PTLOMS/TB105-ERDAT .
    FIELD /PTLOMS/TB105-ERZEIT .
    FIELD /PTLOMS/TB105-AENAM .
    FIELD /PTLOMS/TB105-AEDAT .
    FIELD /PTLOMS/TB105-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB105-ID_NOTIFICACAO .
    FIELD /PTLOMS/TB105-USUARIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
