PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB101 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB101-ID_LISTA .
    FIELD /PTLOMS/TB101-DESCRICAO .
    FIELD /PTLOMS/TB101-ATIVO .
    FIELD /PTLOMS/TB101-ERNAM .
    FIELD /PTLOMS/TB101-ERDAT .
    FIELD /PTLOMS/TB101-ERZEIT .
    FIELD /PTLOMS/TB101-AENAM .
    FIELD /PTLOMS/TB101-AEDAT .
    FIELD /PTLOMS/TB101-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB101-ID_LISTA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
