PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB091 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB091-USUARIO .
    FIELD /PTLOMS/TB091-RESTR_ID .
    FIELD /PTLOMS/TB091-ERNAM .
    FIELD /PTLOMS/TB091-ERDAT .
    FIELD /PTLOMS/TB091-ERZEIT .
    FIELD /PTLOMS/TB091-AENAM .
    FIELD /PTLOMS/TB091-AEDAT .
    FIELD /PTLOMS/TB091-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB091-USUARIO .
    FIELD /PTLOMS/TB091-RESTR_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
