PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB063 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB063-PERFIL .
    FIELD /PTLOMS/TB063-NRSEQ .
    FIELD /PTLOMS/TB063-PLNTY .
    FIELD /PTLOMS/TB063-PLNNR .
    FIELD /PTLOMS/TB063-PLNAL .
    FIELD /PTLOMS/TB063-ZAEHL .
    FIELD /PTLOMS/TB063-KTEXT .
    FIELD /PTLOMS/TB063-STATU .
    FIELD /PTLOMS/TB063-LOEKZ .
    FIELD /PTLOMS/TB063-WERKS .
    FIELD /PTLOMS/TB063-EQUNR .
    FIELD /PTLOMS/TB063-EQKTX .
    FIELD /PTLOMS/TB063-TPLNR .
    FIELD /PTLOMS/TB063-PLTXT .
    FIELD /PTLOMS/TB063-TXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB063-PERFIL .
    FIELD /PTLOMS/TB063-NRSEQ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
