PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB072 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE z_busca_descricao.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB072-APLICACAO .
    FIELD /PTLOMS/TB072-OPCAO .
    FIELD /PTLOMS/TB072-DESCRICAO .
    FIELD /PTLOMS/TB072-ERNAM .
    FIELD /PTLOMS/TB072-ERDAT .
    FIELD /PTLOMS/TB072-ERZEIT .
    FIELD /PTLOMS/TB072-AENAM .
    FIELD /PTLOMS/TB072-AEDAT .
    FIELD /PTLOMS/TB072-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB072-APLICACAO .
    FIELD /PTLOMS/TB072-OPCAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
