PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB074 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE z_descricoes.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB074-APLICACAO .
    FIELD /PTLOMS/TB074-OPCAO .
    FIELD /PTLOMS/TB074-SEQUENCIAL .
    FIELD /PTLOMS/TB074-DESCRICAO .
    FIELD /PTLOMS/TB074-ERNAM .
    FIELD /PTLOMS/TB074-ERDAT .
    FIELD /PTLOMS/TB074-ERZEIT .
    FIELD /PTLOMS/TB074-AENAM .
    FIELD /PTLOMS/TB074-AEDAT .
    FIELD /PTLOMS/TB074-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB074-APLICACAO .
    FIELD /PTLOMS/TB074-OPCAO .
    FIELD /PTLOMS/TB074-SEQUENCIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
