PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB078 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB078-USUARIO .
    FIELD /PTLOMS/TB078-MATRICULA .
    FIELD /PTLOMS/TB078-PERFIL .
    FIELD /PTLOMS/TB078-LATITUDE .
    FIELD /PTLOMS/TB078-LONGITUDE .
    FIELD /PTLOMS/TB078-EVENTO .
    FIELD /PTLOMS/TB078-DATA_COLETA .
    FIELD /PTLOMS/TB078-HORA_COLETA .
    FIELD /PTLOMS/TB078-DATA_CRIACAO .
    FIELD /PTLOMS/TB078-HORA_CRIACAO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB078-USUARIO .
    FIELD /PTLOMS/TB078-MATRICULA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
