PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/PTLOMS/TB076 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /PTLOMS/TB076-APLICACAO .
    FIELD /PTLOMS/TB076-DESCR_VINCULO .
    FIELD /PTLOMS/TB076-OPERACAO .
    FIELD /PTLOMS/TB076-ORDEM .
    FIELD /PTLOMS/TB076-TP_VINCULO .
    FIELD /PTLOMS/TB076-USUARIO .
    FIELD /PTLOMS/TB076-ORDENACAO1 .
    FIELD /PTLOMS/TB076-ORDENACAO2 .
    FIELD /PTLOMS/TB076-DESCR_GRUPO .
    FIELD /PTLOMS/TB076-DESCRICAO .
    FIELD /PTLOMS/TB076-FORMULARIO .
    FIELD /PTLOMS/TB076-GRUPO .
    FIELD /PTLOMS/TB076-OBRIGATORIO .
    FIELD /PTLOMS/TB076-OPCAO .
    FIELD /PTLOMS/TB076-RESPOSTA .
    FIELD /PTLOMS/TB076-RESPOSTA_LOGICA .
    FIELD /PTLOMS/TB076-RESPOSTA_USUARIO .
    FIELD /PTLOMS/TB076-SEQUENCIAL .
    FIELD /PTLOMS/TB076-STATUS .
    FIELD /PTLOMS/TB076-INF_COMPLEMENTAR .
    FIELD /PTLOMS/TB076-ERNAM .
    FIELD /PTLOMS/TB076-ERDAT .
    FIELD /PTLOMS/TB076-ERZEIT .
    FIELD /PTLOMS/TB076-AENAM .
    FIELD /PTLOMS/TB076-AEDAT .
    FIELD /PTLOMS/TB076-AEZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /PTLOMS/TB076-APLICACAO .
    FIELD /PTLOMS/TB076-DESCR_VINCULO .
    FIELD /PTLOMS/TB076-OPERACAO .
    FIELD /PTLOMS/TB076-ORDEM .
    FIELD /PTLOMS/TB076-TP_VINCULO .
    FIELD /PTLOMS/TB076-USUARIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
